#!/bin/bash

## Version
wget -O $HOME/LICENSE.txt https://raw.githubusercontent.com/PechScript/PechVPN.Cloud/PechVPN/LICENSE.txt &> /dev/null
wget -O $HOME/versao https://raw.githubusercontent.com/PechScript/PechVPN.Cloud/PechVPN/versao &> /dev/null
wget -O /bin/versao_script https://raw.githubusercontent.com/PechScript/PechVPN.Cloud/PechVPN/Install/versaoatt &> /dev/null

## Systemverify
rm -rf $HOME/systemverify* &> /dev/null




 
